import LocalFireDepartmentIcon from "@mui/icons-material/LocalFireDepartment";

export const CategoryData = [
  {
    id: 1,
    title: "Adventure",
    description: "",
    path: "/category/adventure",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/adventure.jpg",
  },
  {
    id: 2,
    title: "Comedy",
    description: "",
    path: "/category/comedy",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/comedy.jpg",
  },
  {
    id: 3,
    title: "Horror",
    description: "",
    path: "/category/horror",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/horror.jpg",
  },
  {
    id: 4,
    title: "Mystery",
    description: "",
    path: "/category/mystery",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/mystery.jpg",
  },
  {
    id: 5,
    title: "Romance",
    description: "",
    path: "/category/romance",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/romance.jpg",
  },
  {
    id: 6,
    title: "Slice of Life",
    description: "",
    path: "/category/slice-of-life",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/slice-of-life.jpg",
  },
  {
    id: 7,
    title: "Thriller",
    description: "",
    path: "/category/thriller",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/thriller.jpg",
  },
  {
    id: 8,
    title: "Vlog",
    description: "",
    path: "/category/vlog",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/vlog.jpg",
  },
  {
    id: 9,
    title: "Vlog",
    description: "",
    path: "/category/vlog",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/vlog.jpg",
  },
  {
    id: 10,
    title: "Vlog",
    description: "",
    path: "/category/vlog",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/vlog.jpg",
  },
  {
    id: 11,
    title: "Vlog",
    description: "",
    path: "/category/vlog",
    icon: <LocalFireDepartmentIcon />,
    imageUrl: "/category/vlog.jpg",
  },
];
